// ========================================
// TWENZEE - Products Data
// Gen Z Men's Fashion Collection
// ========================================

const products = [
  {
    id: 1,
    name: "Zenith Oversized Hoodie",
    price: 4999,
    originalPrice: 6499,
    category: "hoodies",
    sizes: ["S","M","L","XL","XXL"],
    images: ["assets/images/product-1.jpg"],
    rating: 4.8,
    reviewCount: 128,
    description: "Premium cotton oversized hoodie with minimalist logo design. Made from high-quality cotton blend for ultimate comfort and style.",
    features: ["100% Premium Cotton", "Oversized Fit", "Minimalist Logo", "Kangaroo Pocket"],
    inStock: true,
    isNew: true,
    isTrending: true
  },
  {
    id: 2,
    name: "Urban Echoes Graphic Hoodie",
    price: 5499,
    originalPrice: 6999,
    category: "hoodies",
    sizes: ["S","M","L","XL"],
    images: ["assets/images/product-2.jpg"],
    rating: 4.7,
    reviewCount: 96,
    description: "Statement graphic hoodie featuring bold urban artwork. Perfect for making a statement.",
    features: ["Bold Graphic Print", "Cotton Blend", "Drawstring Hood", "Ribbed Cuffs"],
    inStock: true,
    isNew: false,
    isTrending: true
  },
  {
    id: 3,
    name: "Midnight Runner Jacket",
    price: 8999,
    originalPrice: 12999,
    category: "jackets",
    sizes: ["S","M","L","XL","XXL"],
    images: ["assets/images/product-3.jpg"],
    rating: 4.9,
    reviewCount: 64,
    description: "Sleek windbreaker jacket perfect for evening runs and night outs. Reflective details for visibility.",
    features: ["Water Resistant", "Reflective Strips", "Lightweight", "Zipper Closure"],
    inStock: true,
    isNew: true,
    isTrending: true
  },
  {
    id: 4,
    name: "Classic Denim Jacket",
    price: 7499,
    originalPrice: 9999,
    category: "jackets",
    sizes: ["M","L","XL"],
    images: ["assets/images/product-4.jpg"],
    rating: 4.5,
    reviewCount: 89,
    description: "Timeless denim jacket with modern cut. A wardrobe essential for every season.",
    features: ["100% Denim", "Button Closure", "Multiple Pockets", "Regular Fit"],
    inStock: true,
    isNew: false,
    isTrending: false
  },
  {
    id: 5,
    name: "Urban Cargo Pants",
    price: 4599,
    originalPrice: 5999,
    category: "pants",
    sizes: ["S","M","L","XL","XXL"],
    images: ["assets/images/product-5.jpg"],
    rating: 4.6,
    reviewCount: 112,
    description: "Versatile cargo pants with multiple pockets. Perfect for street style and outdoor adventures.",
    features: ["Multiple Pockets", "Adjustable Waist", "Durable Fabric", "Cuffed Ankles"],
    inStock: true,
    isNew: true,
    isTrending: true
  },
  {
    id: 6,
    name: "Slim Fit Chinos",
    price: 3299,
    originalPrice: 4499,
    category: "pants",
    sizes: ["S","M","L","XL"],
    images: ["assets/images/product-6.jpg"],
    rating: 4.4,
    reviewCount: 76,
    description: "Clean and classic chino pants with a modern slim fit. Perfect for casual and semi-formal occasions.",
    features: ["Slim Fit", "Cotton Twill", "Side Pockets", "Belt Loops"],
    inStock: true,
    isNew: false,
    isTrending: false
  },
  {
    id: 7,
    name: "Basic White Tee",
    price: 1499,
    originalPrice: 1999,
    category: "tshirts",
    sizes: ["S","M","L","XL","XXL"],
    images: ["assets/images/product-7.jpg"],
    rating: 4.7,
    reviewCount: 245,
    description: "Essential white tee made from premium organic cotton. A wardrobe staple.",
    features: ["100% Organic Cotton", "Crew Neck", "Regular Fit", "Pre-Shrunk"],
    inStock: true,
    isNew: false,
    isTrending: true
  },
  {
    id: 8,
    name: "Graphic Print Tee",
    price: 1899,
    originalPrice: 2499,
    category: "tshirts",
    sizes: ["S","M","L","XL"],
    images: ["assets/images/product-8.jpg"],
    rating: 4.5,
    reviewCount: 156,
    description: "Eye-catching graphic tee with unique design. Express yourself through your style.",
    features: ["Cotton Blend", "Screen Print", "Crew Neck", "Short Sleeve"],
    inStock: true,
    isNew: true,
    isTrending: true
  },
  {
    id: 9,
    name: "Street Runner Sneakers",
    price: 7999,
    originalPrice: 10999,
    category: "footwear",
    sizes: ["40","41","42","43","44","45"],
    images: ["assets/images/product-9.jpg"],
    rating: 4.8,
    reviewCount: 92,
    description: "Comfortable sneakers designed for city streets. Lightweight with excellent cushioning.",
    features: ["Memory Foam Insole", "Rubber Sole", "Breathable Mesh", "Slip-On Design"],
    inStock: true,
    isNew: true,
    isTrending: true
  },
  {
    id: 10,
    name: "Classic Leather Boots",
    price: 12499,
    originalPrice: 15999,
    category: "footwear",
    sizes: ["40","41","42","43","44"],
    images: ["assets/images/product-10.jpg"],
    rating: 4.9,
    reviewCount: 48,
    description: "Premium leather boots for the modern gentleman. Perfect for formal and casual occasions.",
    features: ["Genuine Leather", "Durable Sole", "Comfort Lining", "Classic Design"],
    inStock: true,
    isNew: false,
    isTrending: false
  },
  {
    id: 11,
    name: "Knit Sweater",
    price: 5999,
    originalPrice: 7999,
    category: "knitwear",
    sizes: ["S","M","L","XL"],
    images: ["assets/images/product-11.jpg"],
    rating: 4.6,
    reviewCount: 67,
    description: "Cozy knit sweater perfect for layering. Soft fabric for maximum comfort.",
    features: ["Wool Blend", "Ribbed Details", "Crew Neck", "Long Sleeve"],
    inStock: true,
    isNew: false,
    isTrending: true
  },
  {
    id: 12,
    name: "Velvet Blazer",
    price: 8999,
    originalPrice: 11999,
    category: "formal",
    sizes: ["S","M","L","XL","XXL"],
    images: ["assets/images/product-12.jpg"],
    rating: 4.7,
    reviewCount: 54,
    description: "Luxurious velvet blazer for special occasions. Stand out with premium quality.",
    features: ["Premium Velvet", "Single Breasted", "Peak Lapels", "Interior Pocket"],
    inStock: true,
    isNew: true,
    isTrending: false
  },
  {
    id: 13,
    name: "Leather Belt",
    price: 1299,
    originalPrice: 1799,
    category: "accessories",
    sizes: ["S","M","L","XL"],
    images: ["assets/images/product-13.jpg"],
    rating: 4.3,
    reviewCount: 189,
    description: "Genuine leather belt with sleek buckle. The perfect finishing touch.",
    features: ["Genuine Leather", "Metal Buckle", "Adjustable", "Durable"],
    inStock: true,
    isNew: false,
    isTrending: false
  },
  {
    id: 14,
    name: "Snapback Cap",
    price: 999,
    originalPrice: 1499,
    category: "accessories",
    sizes: ["One Size"],
    images: ["assets/images/product-14.jpg"],
    rating: 4.5,
    reviewCount: 134,
    description: "Classic snapback cap with embroidered logo. Elevate any outfit.",
    features: ["Cotton Blend", "Adjustable Snap", "Embroidered Logo", "Structured Crown"],
    inStock: true,
    isNew: false,
    isTrending: true
  },
  {
    id: 15,
    name: "Aviator Sunglasses",
    price: 2499,
    originalPrice: 3499,
    category: "accessories",
    sizes: ["One Size"],
    images: ["assets/images/product-15.jpg"],
    rating: 4.8,
    reviewCount: 78,
    description: "Classic aviator sunglasses with UV protection. Timeless style meets modern protection.",
    features: ["UV400 Protection", "Metal Frame", "Lens Width: 58mm", "Hard Case Included"],
    inStock: true,
    isNew: true,
    isTrending: true
  },
  {
    id: 16,
    name: "Tech Fleece Hoodie",
    price: 5499,
    originalPrice: 6999,
    category: "hoodies",
    sizes: ["S","M","L","XL","XXL"],
    images: ["assets/images/product-16.jpg"],
    rating: 4.7,
    reviewCount: 88,
    description: "Premium tech fleece hoodie with moisture-wicking properties. Perfect for workouts.",
    features: ["Tech Fleece", "Moisture Wicking", "Zipper Pockets", "Hood with Drawstring"],
    inStock: true,
    isNew: true,
    isTrending: true
  },
  {
    id: 17,
    name: "Bomber Jacket",
    price: 7999,
    originalPrice: 10999,
    category: "jackets",
    sizes: ["S","M","L","XL"],
    images: ["assets/images/product-17.jpg"],
    rating: 4.6,
    reviewCount: 72,
    description: "Classic bomber jacket with ribbed collar and cuffs. Vintage-inspired modern style.",
    features: ["Ribbed Collar", "Zipper Closure", "Side Pockets", "Quilted Lining"],
    inStock: true,
    isNew: false,
    isTrending: false
  },
  {
    id: 18,
    name: "Jogger Pants",
    price: 2899,
    originalPrice: 3999,
    category: "pants",
    sizes: ["S","M","L","XL","XXL"],
    images: ["assets/images/product-18.jpg"],
    rating: 4.5,
    reviewCount: 145,
    description: "Comfortable jogger pants with elastic waistband. Perfect for lounging and casual wear.",
    features: ["Elastic Waist", "Side Pockets", "Cuffed Ankles", "Soft Fabric"],
    inStock: true,
    isNew: false,
    isTrending: true
  },
  {
    id: 19,
    name: "Polo Shirt",
    price: 2199,
    originalPrice: 2999,
    category: "tshirts",
    sizes: ["S","M","L","XL"],
    images: ["assets/images/product-19.jpg"],
    rating: 4.4,
    reviewCount: 98,
    description: "Classic polo shirt with embroidered logo. Smart casual essential.",
    features: ["Cotton Piqué", "Embroidered Logo", "Two Button Placket", "Short Sleeve"],
    inStock: true,
    isNew: false,
    isTrending: false
  },
  {
    id: 20,
    name: "Canvas Sneakers",
    price: 4499,
    originalPrice: 5999,
    category: "footwear",
    sizes: ["40","41","42","43","44","45"],
    images: ["assets/images/product-20.jpg"],
    rating: 4.6,
    reviewCount: 112,
    description: "Classic canvas sneakers for everyday wear. Timeless design meets comfort.",
    features: ["Canvas Upper", "Rubber Sole", "Lace-Up", "Vulcanized Construction"],
    inStock: true,
    isNew: false,
    isTrending: true
  },
  {
    id: 21,
    name: "Wool Scarf",
    price: 1799,
    originalPrice: 2499,
    category: "accessories",
    sizes: ["One Size"],
    images: ["assets/images/product-21.jpg"],
    rating: 4.7,
    reviewCount: 56,
    description: "Soft wool scarf for cold weather. Stay warm in style.",
    features: ["100% Wool", "Fringed Edges", "Machine Washable", "Multiple Colors"],
    inStock: true,
    isNew: false,
    isTrending: false
  },
  {
    id: 22,
    name: "Leather Wallet",
    price: 1499,
    originalPrice: 1999,
    category: "accessories",
    sizes: ["One Size"],
    images: ["assets/images/product-22.jpg"],
    rating: 4.5,
    reviewCount: 167,
    description: "Slim leather wallet with card slots. Minimalist design for the modern man.",
    features: ["Genuine Leather", "Card Slots", "Bill Compartment", "RFID Blocking"],
    inStock: true,
    isNew: false,
    isTrending: false
  },
  {
    id: 23,
    name: "Puffer Vest",
    price: 3999,
    originalPrice: 5499,
    category: "jackets",
    sizes: ["S","M","L","XL","XXL"],
    images: ["assets/images/product-23.jpg"],
    rating: 4.6,
    reviewCount: 84,
    description: "Lightweight puffer vest for layering. Perfect for transitional weather.",
    features: ["Lightweight", "Quilted Design", "Zipper Pockets", "Stand Collar"],
    inStock: true,
    isNew: true,
    isTrending: true
  },
  {
    id: 24,
    name: "Skinny Jeans",
    price: 3499,
    originalPrice: 4499,
    category: "pants",
    sizes: ["S","M","L","XL"],
    images: ["assets/images/product-24.jpg"],
    rating: 4.4,
    reviewCount: 132,
    description: "Modern skinny jeans with stretch. Sleek silhouette for the fashion-forward.",
    features: ["Stretch Denim", "Skinny Fit", "5 Pocket Style", "Zip Fly"],
    inStock: true,
    isNew: false,
    isTrending: false
  }
];

// Categories
const categories = [
  { id: 'all', name: 'All Products', icon: 'fa-th-large' },
  { id: 'hoodies', name: 'Hoodies & Sweatshirts', icon: 'fa-tshirt' },
  { id: 'tshirts', name: 'T-Shirts', icon: 'fa-tshirt' },
  { id: 'jackets', name: 'Jackets & Coats', icon: 'fa-user-tie' },
  { id: 'pants', name: 'Pants & Jeans', icon: 'fa-drumstick-bite' },
  { id: 'formal', name: 'Formal Wear', icon: 'fa-user-tie' },
  { id: 'knitwear', name: 'Knitwear', icon: 'fa-snowflake' },
  { id: 'footwear', name: 'Footwear', icon: 'fa-shoe-prints' },
  { id: 'accessories', name: 'Accessories', icon: 'fa-glasses' }
];

// Helpers
const getProductById = (id) => products.find(p => p.id === parseInt(id));
const getProductsByCategory = (cat) => cat === 'all' ? products : products.filter(p => p.category === cat);
const getTrendingProducts = () => products.filter(p => p.isTrending).slice(0,8);
const getNewArrivals = () => products.filter(p => p.isNew).slice(0,8);
const formatPrice = (price) => new Intl.NumberFormat('en-PK',{style:'currency',currency:'PKR',minimumFractionDigits:0}).format(price);
const searchProducts = (query) => {
  const q = query.toLowerCase();
  return products.filter(p => p.name.toLowerCase().includes(q) || p.category.toLowerCase().includes(q) || p.description.toLowerCase().includes(q));
};

// Export
window.products = products;
window.categories = categories;
window.getProductById = getProductById;
window.getProductsByCategory = getProductsByCategory;
window.getTrendingProducts = getTrendingProducts;
window.getNewArrivals = getNewArrivals;
window.formatPrice = formatPrice;
window.searchProducts = searchProducts;
